version: '3.3'
services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   PUBLIC_API_URL: https://localhost:8002
    image: drnuxt
    container_name: drnuxt
    restart: always
    # command: npm run dev
    # volumes:
    # - .:/app
    # - /app/node_modules
    # volumes:
    #   - .:/var/www/html/druzhba-nn.site
    #   - "/var/www/html/druzhba-nn.site/node_modules"
    ports:
      - 8002:3000